---
title: "Gene_ontology_BP_enrichment_analysis"
author: "Sreemol Gokuladhas"
date: "25/03/2021"
output: html_document
---

```{r}
## set working directory

setwd("/Genetics_of_autoimmune_diseases/scripts/R")

## Load gene information file

map <- read.delim("../../data/map_file_short.txt", sep = "\t", header = T)

```

```{r}

##### Cluster216 ontology analysis - Module1 #####

cluster216 <- read.delim("../../data/cluster_ids/module1_p216_ids.txt", header = F)
names(cluster216) = "id"

##get gene names corresponding to the ID

cluster216_symbol <- merge(map, cluster216, by = "id")

library(gprofiler2)
go_cluster216 <- gost(query = unique(cluster216_symbol$name),
                               numeric_ns = "ENTREZGENE_ACC",
                               organism = "hsapiens",
                               ordered_query = F,
                               significant = T,
                               measure_underrepresentation = F,
                               evcodes = T,
                               user_threshold = 0.05,
                               correction_method = "fdr",
                               domain_scope = "annotated")

## put GO results into a dataframe

go_cluster216_df <- head(go_cluster216$result, 100000)

## Subset only required columns 

go_cluster216_df_subset <- go_cluster216_df[,c("term_id", "term_name", "query_size", "intersection_size",
                                              "p_value", "intersection", "source")]

## Subset only GO:BP results

go_cluster216_bp <- go_cluster216_df_subset[grep('GO:BP', go_cluster216_df_subset$source), ]

## order by p_value

c216_order_pval <- go_cluster216_bp[order(go_cluster216_bp$p_value),]

## write the results to a file

write.table(c216_order_pval, file = "../../results/go_results/mod1_c216_bp_ordered_res.txt", sep = "\t", row.names = FALSE, col.names = T, quote= FALSE)



##### Cluster345 ontology enrichment analysis - Module2 #####

cluster345 <- read.delim("../../data/cluster_ids/module2_p345_ids.txt", header = F)
names(cluster345) = "id"

##get gene names corresponding to the ID

cluster345_symbol <- merge(map, cluster345, by = "id")

library(gprofiler2)
go_cluster345 <- gost(query = unique(cluster345_symbol$name),
                               numeric_ns = "ENTREZGENE_ACC",
                               organism = "hsapiens",
                               ordered_query = F,
                               significant = T,
                               measure_underrepresentation = F,
                               evcodes = T,
                               user_threshold = 0.05,
                               correction_method = "fdr",
                               domain_scope = "annotated")

## put GO results into a dataframe

go_cluster345_df <- head(go_cluster345$result, 100000)

## Subset only required columns 

go_cluster345_df_subset <- go_cluster345_df[,c("term_id", "term_name", "query_size", "intersection_size",
                                              "p_value", "intersection", "source")]

## Subset only GO:BP results

go_cluster345_bp <- go_cluster345_df_subset[grep('GO:BP', go_cluster345_df_subset$source), ]

## order by p_value

c345_order_pval <- go_cluster345_bp[order(go_cluster345_bp$p_value),]

## write the results to a file

write.table(c345_order_pval, file = "../../results/go_results/mod2_c345_bp_ordered_res.txt", sep = "\t", row.names = FALSE, col.names = T, quote= FALSE)



##### Cluster164 ontology enrichment analysis - Module3 #####

cluster164 <- read.delim("../../data/cluster_ids/module3_p164_ids.txt", header = F)
names(cluster164) = "id"

##get gene names corresponding to the ID

cluster164_symbol <- merge(map, cluster164, by = "id")

library(gprofiler2)
go_cluster164 <- gost(query = unique(cluster164_symbol$name),
                               numeric_ns = "ENTREZGENE_ACC",
                               organism = "hsapiens",
                               ordered_query = F,
                               significant = T,
                               measure_underrepresentation = F,
                               evcodes = T,
                               user_threshold = 0.05,
                               correction_method = "fdr",
                               domain_scope = "annotated")

## put GO results into a dataframe

go_cluster164_df <- head(go_cluster164$result, 100000)

## Subset only required columns 

go_cluster164_df_subset <- go_cluster164_df[,c("term_id", "term_name", "query_size", "intersection_size",
                                              "p_value", "intersection", "source")]

## Subset only GO:BP results

go_cluster164_bp <- go_cluster164_df_subset[grep('GO:BP', go_cluster164_df_subset$source), ]

## order by p_value

c164_order_pval <- go_cluster164_bp[order(go_cluster164_bp$p_value),]

## write the results to a file

write.table(c164_order_pval, file = "../../results/go_results/mod3_c164_bp_ordered_res.txt", sep = "\t", row.names = FALSE, col.names = T, quote= FALSE)



##### Cluster171 ontology enrichment analysis - Module4 #####

cluster171 <- read.delim("../../data/cluster_ids/module4_p171_ids.txt", header = F)
names(cluster171) = "id"

##get gene names corresponding to the ID

cluster171_symbol <- merge(map, cluster171, by = "id")

library(gprofiler2)
go_cluster171 <- gost(query = unique(cluster171_symbol$name),
                               numeric_ns = "ENTREZGENE_ACC",
                               organism = "hsapiens",
                               ordered_query = F,
                               significant = T,
                               measure_underrepresentation = F,
                               evcodes = T,
                               user_threshold = 0.05,
                               correction_method = "fdr",
                               domain_scope = "annotated")

## put GO results into a dataframe

go_cluster171_df <- head(go_cluster171$result, 100000)

## Subset only required columns 

go_cluster171_df_subset <- go_cluster171_df[,c("term_id", "term_name", "query_size", "intersection_size",
                                              "p_value", "intersection", "source")]

## Subset only GO:BP results

go_cluster171_bp <- go_cluster171_df_subset[grep('GO:BP', go_cluster171_df_subset$source), ]

## order by p_value

c171_order_pval <- go_cluster171_bp[order(go_cluster171_bp$p_value),]

## write the results to a file

write.table(c171_order_pval, file = "../../results/go_results/mod4_c171_bp_ordered_res.txt", sep = "\t", row.names = FALSE, col.names = T, quote= FALSE)



##### Cluster177 ontology enrichment analysis - Module5 #####

cluster177 <- read.delim("../../data/cluster_ids/module5_p177_ids.txt", header = F)
names(cluster177) = "id"

##get gene names corresponding to the ID

cluster177_symbol <- merge(map, cluster177, by = "id")

library(gprofiler2)
go_cluster177 <- gost(query = unique(cluster177_symbol$name),
                               numeric_ns = "ENTREZGENE_ACC",
                               organism = "hsapiens",
                               ordered_query = F,
                               significant = T,
                               measure_underrepresentation = F,
                               evcodes = T,
                               user_threshold = 0.05,
                               correction_method = "fdr",
                               domain_scope = "annotated")

## put GO results into a dataframe

go_cluster177_df <- head(go_cluster177$result, 100000)

## Subset only required columns 

go_cluster177_df_subset <- go_cluster177_df[,c("term_id", "term_name", "query_size", "intersection_size",
                                              "p_value", "intersection", "source")]

## Subset only GO:BP results

go_cluster177_bp <- go_cluster177_df_subset[grep('GO:BP', go_cluster177_df_subset$source), ]

## order by p_value

c177_order_pval <- go_cluster177_bp[order(go_cluster177_bp$p_value),]

## write the results to a file

write.table(c177_order_pval, file = "../../results/go_results/mod5_c177_bp_ordered_res.txt", sep = "\t", row.names = FALSE, col.names = T, quote= FALSE)




##### Cluster194 ontology enrichment analysis - Module6 #####

cluster194 <- read.delim("../../data/cluster_ids/module6_p194_ids.txt", header = F)
names(cluster194) = "id"

##get gene names corresponding to the ID

cluster194_symbol <- merge(map, cluster194, by = "id")

library(gprofiler2)
go_cluster194 <- gost(query = unique(cluster194_symbol$name),
                               numeric_ns = "ENTREZGENE_ACC",
                               organism = "hsapiens",
                               ordered_query = F,
                               significant = T,
                               measure_underrepresentation = F,
                               evcodes = T,
                               user_threshold = 0.05,
                               correction_method = "fdr",
                               domain_scope = "annotated")

## put GO results into a dataframe

go_cluster194_df <- head(go_cluster194$result, 100000)

## Subset only required columns 

go_cluster194_df_subset <- go_cluster194_df[,c("term_id", "term_name", "query_size", "intersection_size",
                                              "p_value", "intersection", "source")]

## Subset only GO:BP results

go_cluster194_bp <- go_cluster194_df_subset[grep('GO:BP', go_cluster194_df_subset$source), ]

## order by p_value

c194_order_pval <- go_cluster194_bp[order(go_cluster194_bp$p_value),]

## write the results to a file

write.table(c194_order_pval, file = "../../results/go_results/mod6_c194_bp_ordered_res.txt", sep = "\t", row.names = FALSE, col.names = T, quote= FALSE)




##### Cluster472 ontology enrichment analysis - Module7 #####

cluster472 <- read.delim("../../data/cluster_ids/module7_p472_ids.txt", header = F)
names(cluster472) = "id"

##get gene names corresponding to the ID

cluster472_symbol <- merge(map, cluster472, by = "id")

library(gprofiler2)
go_cluster472 <- gost(query = unique(cluster472_symbol$name),
                               numeric_ns = "ENTREZGENE_ACC",
                               organism = "hsapiens",
                               ordered_query = F,
                               significant = T,
                               measure_underrepresentation = F,
                               evcodes = T,
                               user_threshold = 0.05,
                               correction_method = "fdr",
                               domain_scope = "annotated")

## put GO results into a dataframe

go_cluster472_df <- head(go_cluster472$result, 100000)

## Subset only required columns 

go_cluster472_df_subset <- go_cluster472_df[,c("term_id", "term_name", "query_size", "intersection_size",
                                              "p_value", "intersection", "source")]

## Subset only GO:BP results

go_cluster472_bp <- go_cluster472_df_subset[grep('GO:BP', go_cluster472_df_subset$source), ]

## order by p_value

c472_order_pval <- go_cluster472_bp[order(go_cluster472_bp$p_value),]

## write the results to a file

write.table(c472_order_pval, file = "../../results/go_results/mod7_c472_bp_ordered_res.txt", sep = "\t", row.names = FALSE, col.names = T, quote= FALSE)




##### Cluster170 ontology enrichment analysis - Module8 #####

cluster170 <- read.delim("/Volumes/MyHome/autoimmune_project_new/analysis/network_analysis/cluster_text_files/cluster170.txt", header = F)
names(cluster170) = "id"

##get gene names corresponding to the ID

cluster170_symbol <- merge(map, cluster170, by = "id")

library(gprofiler2)
go_cluster170 <- gost(query = unique(cluster170_symbol$name),
                               numeric_ns = "ENTREZGENE_ACC",
                               organism = "hsapiens",
                               ordered_query = F,
                               significant = T,
                               measure_underrepresentation = F,
                               evcodes = T,
                               user_threshold = 0.05,
                               correction_method = "fdr",
                               domain_scope = "annotated")

## put GO results into a dataframe

go_cluster170_df <- head(go_cluster170$result, 100000)

## Subset only required columns 

go_cluster170_df_subset <- go_cluster170_df[,c("term_id", "term_name", "query_size", "intersection_size",
                                              "p_value", "intersection", "source")]

## Subset only GO:BP results

go_cluster170_bp <- go_cluster170_df_subset[grep('GO:BP', go_cluster170_df_subset$source), ]

## order by p_value

c170_order_pval <- go_cluster170_bp[order(go_cluster170_bp$p_value),]

## write the results to a file

write.table(c170_order_pval, file = "../../results/go_results/mod8_c170_bp_ordered_res.txt", sep = "\t", row.names = FALSE, col.names = T, quote= FALSE)




##### Cluster122 ontology enrichment analysis - Module9 #####

cluster122 <- read.delim("../../data/cluster_ids/module9_p122_ids.txt", header = F)
names(cluster122) = "id"

##get gene names corresponding to the ID

cluster122_symbol <- merge(map, cluster122, by = "id")

library(gprofiler2)
go_cluster122 <- gost(query = unique(cluster122_symbol$name),
                               numeric_ns = "ENTREZGENE_ACC",
                               organism = "hsapiens",
                               ordered_query = F,
                               significant = T,
                               measure_underrepresentation = F,
                               evcodes = T,
                               user_threshold = 0.05,
                               correction_method = "fdr",
                               domain_scope = "annotated")

## put GO results into a dataframe

go_cluster122_df <- head(go_cluster122$result, 100000)

## Subset only required columns 

go_cluster122_df_subset <- go_cluster122_df[,c("term_id", "term_name", "query_size", "intersection_size",
                                              "p_value", "intersection", "source")]

## Subset only GO:BP results

go_cluster122_bp <- go_cluster122_df_subset[grep('GO:BP', go_cluster122_df_subset$source), ]

## order by p_value

c122_order_pval <- go_cluster122_bp[order(go_cluster122_bp$p_value),]

## write the results to a file

write.table(c122_order_pval, file = "../../results/go_results/mod9_c122_bp_ordered_res.txt", sep = "\t", row.names = FALSE, col.names = T, quote= FALSE)




##### Cluster79 ontology enrichment analysis - Module10 #####

cluster79 <- read.delim("../../data/cluster_ids/module10_p79_ids.txt", header = F)
names(cluster79) = "id"

##get gene names corresponding to the ID

cluster79_symbol <- merge(map, cluster79, by = "id")

library(gprofiler2)
go_cluster79 <- gost(query = unique(cluster79_symbol$name),
                               numeric_ns = "ENTREZGENE_ACC",
                               organism = "hsapiens",
                               ordered_query = F,
                               significant = T,
                               measure_underrepresentation = F,
                               evcodes = T,
                               user_threshold = 0.05,
                               correction_method = "fdr",
                               domain_scope = "annotated")

## put GO results into a dataframe

go_cluster79_df <- head(go_cluster79$result, 100000)

## Subset only required columns 

go_cluster79_df_subset <- go_cluster79_df[,c("term_id", "term_name", "query_size", "intersection_size",
                                              "p_value", "intersection", "source")]

## Subset only GO:BP results

go_cluster79_bp <- go_cluster79_df_subset[grep('GO:BP', go_cluster79_df_subset$source), ]

## order by p_value

c79_order_pval <- go_cluster79_bp[order(go_cluster79_bp$p_value),]

## write the results to a file

write.table(c79_order_pval, file = "../../results/go_results/mod10_c79_bp_ordered_res.txt", sep = "\t", row.names = FALSE, col.names = T, quote= FALSE)




##### Cluster123 ontology enrichment analysis - Module11 #####

cluster123 <- read.delim("../../data/cluster_ids/module11_p123_ids.txt", header = F)
names(cluster123) = "id"

##get gene names corresponding to the ID

cluster123_symbol <- merge(map, cluster123, by = "id")

library(gprofiler2)
go_cluster123 <- gost(query = unique(cluster123_symbol$name),
                               numeric_ns = "ENTREZGENE_ACC",
                               organism = "hsapiens",
                               ordered_query = F,
                               significant = T,
                               measure_underrepresentation = F,
                               evcodes = T,
                               user_threshold = 0.05,
                               correction_method = "fdr",
                               domain_scope = "annotated")

## put GO results into a dataframe

go_cluster123_df <- head(go_cluster123$result, 100000)

## Subset only required columns 

go_cluster123_df_subset <- go_cluster123_df[,c("term_id", "term_name", "query_size", "intersection_size",
                                              "p_value", "intersection", "source")]

## Subset only GO:BP results

go_cluster123_bp <- go_cluster123_df_subset[grep('GO:BP', go_cluster123_df_subset$source), ]

## order by p_value

c123_order_pval <- go_cluster123_bp[order(go_cluster123_bp$p_value),]

## write the results to a file

write.table(c123_order_pval, file = "../../results/go_results/mod11_c123_bp_ordered_res.txt", sep = "\t", row.names = FALSE, col.names = T, quote= FALSE)




##### Cluster220 ontology enrichment analysis - Module12 #####

cluster220 <- read.delim("../../data/cluster_ids/module12_p220_ids.txt", header = F)
names(cluster220) = "id"

##get gene names corresponding to the ID

cluster220_symbol <- merge(map, cluster220, by = "id")

library(gprofiler2)
go_cluster220 <- gost(query = unique(cluster220_symbol$name),
                               numeric_ns = "ENTREZGENE_ACC",
                               organism = "hsapiens",
                               ordered_query = F,
                               significant = T,
                               measure_underrepresentation = F,
                               evcodes = T,
                               user_threshold = 0.05,
                               correction_method = "fdr",
                               domain_scope = "annotated")

## put GO results into a dataframe

go_cluster220_df <- head(go_cluster220$result, 100000)

## Subset only required columns 

go_cluster220_df_subset <- go_cluster220_df[,c("term_id", "term_name", "query_size", "intersection_size",
                                              "p_value", "intersection", "source")]

## Subset only GO:BP results

go_cluster220_bp <- go_cluster220_df_subset[grep('GO:BP', go_cluster220_df_subset$source), ]

## order by p_value

c220_order_pval <- go_cluster220_bp[order(go_cluster220_bp$p_value),]

## write the results to a file

write.table(c220_order_pval, file = "../../results/go_results/mod12_c220_bp_ordered_res.txt", sep = "\t", row.names = FALSE, col.names = T, quote= FALSE)




##### Cluster150 ontology enrichment analysis - Module13 #####

cluster150 <- read.delim("../../data/cluster_ids/module13_p150_ids.txt", header = F)
names(cluster150) = "id"

##get gene names corresponding to the ID

cluster150_symbol <- merge(map, cluster150, by = "id")

library(gprofiler2)
go_cluster150 <- gost(query = unique(cluster150_symbol$name),
                               numeric_ns = "ENTREZGENE_ACC",
                               organism = "hsapiens",
                               ordered_query = F,
                               significant = T,
                               measure_underrepresentation = F,
                               evcodes = T,
                               user_threshold = 0.05,
                               correction_method = "fdr",
                               domain_scope = "annotated")

## put GO results into a dataframe

go_cluster150_df <- head(go_cluster150$result, 100000)

## Subset only required columns 

go_cluster150_df_subset <- go_cluster150_df[,c("term_id", "term_name", "query_size", "intersection_size",
                                              "p_value", "intersection", "source")]

## Subset only GO:BP results

go_cluster150_bp <- go_cluster150_df_subset[grep('GO:BP', go_cluster150_df_subset$source), ]

## order by p_value

c150_order_pval <- go_cluster150_bp[order(go_cluster150_bp$p_value),]

## write the results to a file

write.table(c150_order_pval, file = "../../results/go_results/mod13_c150_bp_ordered_res.txt", sep = "\t", row.names = FALSE, col.names = T, quote= FALSE)




##### Cluster73 ontology enrichment analysis - Module14 #####

cluster73 <- read.delim("../../data/cluster_ids/module14_p73_ids.txt", header = F)
names(cluster73) = "id"

##get gene names corresponding to the ID

cluster73_symbol <- merge(map, cluster73, by = "id")

library(gprofiler2)
go_cluster73 <- gost(query = unique(cluster73_symbol$name),
                               numeric_ns = "ENTREZGENE_ACC",
                               organism = "hsapiens",
                               ordered_query = F,
                               significant = T,
                               measure_underrepresentation = F,
                               evcodes = T,
                               user_threshold = 0.05,
                               correction_method = "fdr",
                               domain_scope = "annotated")

## put GO results into a dataframe

go_cluster73_df <- head(go_cluster73$result, 100000)

## Subset only required columns 

go_cluster73_df_subset <- go_cluster73_df[,c("term_id", "term_name", "query_size", "intersection_size",
                                              "p_value", "intersection", "source")]

## Subset only GO:BP results

go_cluster73_bp <- go_cluster73_df_subset[grep('GO:BP', go_cluster73_df_subset$source), ]

## order by p_value

c73_order_pval <- go_cluster73_bp[order(go_cluster73_bp$p_value),]

## write the results to a file

write.table(c73_order_pval, file = "../../results/go_results/mod14_c73_bp_ordered_res.txt", sep = "\t", row.names = FALSE, col.names = T, quote= FALSE)
```