---
title: "Ai-PPIN_analysis"
author: "Sreemol Gokuladhas"
date: "25/03/2021"
output: html_document
---

```{r}

## The autoimmune protein-protein interaction network (Ai-PPIN) was constructed and modules were identified from it using the python script /scripts/Python/find_significant_module.py

## The entrez ids of the input genes used for the Ai-PPIN is provided in /data/entrez_ids_of_genes_used_for_AiPPIN_construction.txt

## To reproduce the results - run /scripts/Python/find_significant_module.py using network file /data/Human_interactome_STRINGv11.0.txt and the input file /data/entrez_ids_of_genes_used_for_AiPPIN_construction.txt

## The centrality analysis was performed on each significant module identified from the Ai-PPIN. Three centrality measures were used - degree, closeness and eigenvector. Python script used for the centraliy analysis is provided in /scripts/Python/perform_centrality_analysis.py

## The input data used for the centrality analysis is provided in /data/centrality_inputs/

```

```{r}

## Set working directory 

setwd("/Genetics_of_autoimmune_diseases/scripts/R")

## Analysis to identify central nodes (as defined by the top 10% proteins ranked by all three centrality measures) in each modules

## Load the output files (i.e., centrality_scores.txt) generated by perform_centrality_analysis.py 

####### To find central nodes in Module 1 (10% of 216 is 22)

cluster216_cs <- read.delim("../../results/centrality_analysis_results/module1_p216/centrality_scores.txt", header = T, sep = "\t")
names(cluster216_cs)[1] = "id"

# degree centrality

c216_dc <- subset(cluster216_cs, select = c("id", "DC"))
c216_dc_ordered <- c216_dc[order(-c216_dc$DC),]
c216_dc_top10_perc <- head(c216_dc_ordered, 22)

## Closeness centrality  
  
c216_cc <- subset(cluster216_cs, select = c("id", "CC"))
c216_cc_ordered <- c216_cc[order(-c216_cc$CC),]
c216_cc_top10_perc <- head(c216_cc_ordered, 22)

## Eigenvector centrality  
  
c216_ec <- subset(cluster216_cs, select = c("id", "EC"))
c216_ec_ordered <- c216_ec[order(-c216_ec$EC),]
c216_ec_top10_perc <- head(c216_ec_ordered, 22)

## merge all top10 centrality scores

library(reshape)
c216_list <- list(c216_dc_top10_perc, c216_cc_top10_perc, c216_ec_top10_perc)
c216_top10perc_data <- merge_recurse(c216_list)

## Remove the IDs that doesn't have all three centrality values

c216_top10perc_data_tofile <- na.omit(c216_top10perc_data)

## Write the results to file

write.table(c216_top10perc_data_tofile, file = "../../results/centrality_analysis_results/module1_p216/top10percent_genes_in_c216.txt", sep = "\t", row.names = FALSE, col.names = T, quote= FALSE)

####### To find central nodes in Module 2 (10% of 345 is 35)

cluster345_cs <- read.delim("../../results/centrality_analysis_results/module2_p345/centrality_scores.txt", header = T, sep = "\t")
names(cluster345_cs)[1] = "id"

## degree centrality

c345_dc <- subset(cluster345_cs, select = c("id", "DC"))
c345_dc_ordered <- c345_dc[order(-c345_dc$DC),]
c345_dc_top10_perc <- head(c345_dc_ordered, 35)

## Closeness centrality  
  
c345_cc <- subset(cluster345_cs, select = c("id", "CC"))
c345_cc_ordered <- c345_cc[order(-c345_cc$CC),]
c345_cc_top10_perc <- head(c345_cc_ordered, 35)

## Eigenvector centrality  
  
c345_ec <- subset(cluster345_cs, select = c("id", "EC"))
c345_ec_ordered <- c345_ec[order(-c345_ec$EC),]
c345_ec_top10_perc <- head(c345_ec_ordered, 35)

## merge all top10 centrality scores

library(reshape)
c345_list <- list(c345_dc_top10_perc, c345_cc_top10_perc, c345_ec_top10_perc)
c345_top10perc_data <- merge_recurse(c345_list)

## Remove the IDs that doesn't have all three centrality values

c345_top10perc_data_tofile <- na.omit(c345_top10perc_data)

write.table(c345_top10perc_data_tofile, file = "../../results/centrality_analysis_results/module2_p345/top10percent_genes_in_c345.txt", sep = "\t", row.names = FALSE, col.names = T, quote= FALSE)

####### To find central nodes in Module 3 (10% of 164 is 16)

cluster164_cs <- read.delim("../../results/centrality_analysis_results/module3_p164/centrality_scores.txt", header = T, sep = "\t")
names(cluster164_cs)[1] = "id"

## degree centrality

c164_dc <- subset(cluster164_cs, select = c("id", "DC"))
c164_dc_ordered <- c164_dc[order(-c164_dc$DC),]
c164_dc_top10_perc <- head(c164_dc_ordered, 16)

## Closeness centrality  
  
c164_cc <- subset(cluster164_cs, select = c("id", "CC"))
c164_cc_ordered <- c164_cc[order(-c164_cc$CC),]
c164_cc_top10_perc <- head(c164_cc_ordered, 16)

## Eigenvector centrality  
  
c164_ec <- subset(cluster164_cs, select = c("id", "EC"))
c164_ec_ordered <- c164_ec[order(-c164_ec$EC),]
c164_ec_top10_perc <- head(c164_ec_ordered, 16)

## merge all top10 centrality scores

library(reshape)
c164_list <- list(c164_dc_top10_perc, c164_cc_top10_perc, c164_ec_top10_perc)
c164_top10perc_data <- merge_recurse(c164_list)

## Remove the IDs that doesn't have all three centrality values

c164_top10perc_data_tofile <- na.omit(c164_top10perc_data)

write.table(c164_top10perc_data_tofile, file = "../../results/centrality_analysis_results/module3_p164/top10percent_genes_in_c164.txt", sep = "\t", row.names = FALSE, col.names = T, quote= FALSE)

####### To find central nodes in Module 4 (10% of 171 is 17)

cluster171_cs <- read.delim("../../results/centrality_analysis_results/module4_p171/centrality_scores.txt", header = T, sep = "\t")
names(cluster171_cs)[1] = "id"

## degree centrality

c171_dc <- subset(cluster171_cs, select = c("id", "DC"))
c171_dc_ordered <- c171_dc[order(-c171_dc$DC),]
c171_dc_top10_perc <- head(c171_dc_ordered, 17)

## Closeness centrality  
  
c171_cc <- subset(cluster171_cs, select = c("id", "CC"))
c171_cc_ordered <- c171_cc[order(-c171_cc$CC),]
c171_cc_top10_perc <- head(c171_cc_ordered, 17)

## Eigenvector centrality  
  
c171_ec <- subset(cluster171_cs, select = c("id", "EC"))
c171_ec_ordered <- c171_ec[order(-c171_ec$EC),]
c171_ec_top10_perc <- head(c171_ec_ordered, 17)

## merge all top10 centrality scores

library(reshape)
c171_list <- list(c171_dc_top10_perc, c171_cc_top10_perc, c171_ec_top10_perc)
c171_top10perc_data <- merge_recurse(c171_list)

## Remove the IDs that doesn't have all three centrality values

c171_top10perc_data_tofile <- na.omit(c171_top10perc_data)

write.table(c171_top10perc_data_tofile, file = "../../results/centrality_analysis_results/module4_p171/top10percent_genes_in_c171.txt", sep = "\t", row.names = FALSE, col.names = T, quote= FALSE)

####### To find central nodes in Module 5 (10% of 177 is 18)

cluster177_cs <- read.delim("../../results/centrality_analysis_results/module5_p177/centrality_scores.txt", header = T, sep = "\t")
names(cluster177_cs)[1] = "id"

## degree centrality

c177_dc <- subset(cluster177_cs, select = c("id", "DC"))
c177_dc_ordered <- c177_dc[order(-c177_dc$DC),]
c177_dc_top10_perc <- head(c177_dc_ordered, 18)

## Closeness centrality  
  
c177_cc <- subset(cluster177_cs, select = c("id", "CC"))
c177_cc_ordered <- c177_cc[order(-c177_cc$CC),]
c177_cc_top10_perc <- head(c177_cc_ordered, 18)

## Eigenvector centrality  
  
c177_ec <- subset(cluster177_cs, select = c("id", "EC"))
c177_ec_ordered <- c177_ec[order(-c177_ec$EC),]
c177_ec_top10_perc <- head(c177_ec_ordered, 18)

## merge all top10 centrality scores

library(reshape)
c177_list <- list(c177_dc_top10_perc, c177_cc_top10_perc, c177_ec_top10_perc)
c177_top10perc_data <- merge_recurse(c177_list)

## Remove the IDs that doesn't have all three centrality values

c177_top10perc_data_tofile <- na.omit(c177_top10perc_data)

write.table(c177_top10perc_data_tofile, file = "../../results/centrality_analysis_results/module5_p177/top10percent_genes_in_c177.txt", sep = "\t", row.names = FALSE, col.names = T, quote= FALSE)

####### To find central nodes in Module 6 (10% of 194 is 19)

cluster194_cs <- read.delim("../../results/centrality_analysis_results/module6_p194/centrality_scores.txt", header = T, sep = "\t")
names(cluster194_cs)[1] = "id"

## degree centrality

c194_dc <- subset(cluster194_cs, select = c("id", "DC"))
c194_dc_ordered <- c194_dc[order(-c194_dc$DC),]
c194_dc_top10_perc <- head(c194_dc_ordered, 19)

## Closeness centrality  
  
c194_cc <- subset(cluster194_cs, select = c("id", "CC"))
c194_cc_ordered <- c194_cc[order(-c194_cc$CC),]
c194_cc_top10_perc <- head(c194_cc_ordered, 19)

## Eigenvector centrality  
  
c194_ec <- subset(cluster194_cs, select = c("id", "EC"))
c194_ec_ordered <- c194_ec[order(-c194_ec$EC),]
c194_ec_top10_perc <- head(c194_ec_ordered, 19)

## merge all top10 centrality scores

library(reshape)
c194_list <- list(c194_dc_top10_perc, c194_cc_top10_perc, c194_ec_top10_perc)
c194_top10perc_data <- merge_recurse(c194_list)

## Remove the IDs that doesn't have all three centrality values

c194_top10perc_data_tofile <- na.omit(c194_top10perc_data)

write.table(c194_top10perc_data_tofile, file = "../../results/centrality_analysis_results/module6_p194/top10percent_genes_in_c194.txt", sep = "\t", row.names = FALSE, col.names = T, quote= FALSE)

####### To find central nodes in Module 7 (10% of 472 is 47)

cluster472_cs <- read.delim("../../results/centrality_analysis_results/module7_p472/centrality_scores.txt", header = T, sep = "\t")
names(cluster472_cs)[1] = "id"

## degree centrality

c472_dc <- subset(cluster472_cs, select = c("id", "DC"))
c472_dc_ordered <- c472_dc[order(-c472_dc$DC),]
c472_dc_top10_perc <- head(c472_dc_ordered, 47)

## Closeness centrality  
  
c472_cc <- subset(cluster472_cs, select = c("id", "CC"))
c472_cc_ordered <- c472_cc[order(-c472_cc$CC),]
c472_cc_top10_perc <- head(c472_cc_ordered, 47)

## Eigenvector centrality  
  
c472_ec <- subset(cluster472_cs, select = c("id", "EC"))
c472_ec_ordered <- c472_ec[order(-c472_ec$EC),]
c472_ec_top10_perc <- head(c472_ec_ordered, 47)

## merge all top10 centrality scores

library(reshape)
c472_list <- list(c472_dc_top10_perc, c472_cc_top10_perc, c472_ec_top10_perc)
c472_top10perc_data <- merge_recurse(c472_list)

## Remove the IDs that doesn't have all three centrality values

c472_top10perc_data_tofile <- na.omit(c472_top10perc_data)

write.table(c472_top10perc_data_tofile, file = "../../results/centrality_analysis_results/module7_p472/top10percent_genes_in_c472.txt", sep = "\t", row.names = FALSE, col.names = T, quote= FALSE)

####### To find central nodes in Module 8 (10% of 170 is 17)

cluster170_cs <- read.delim("../../results/centrality_analysis_results/module8_p170/centrality_scores.txt", header = T, sep = "\t")
names(cluster170_cs)[1] = "id"

## degree centrality

c170_dc <- subset(cluster170_cs, select = c("id", "DC"))
c170_dc_ordered <- c170_dc[order(-c170_dc$DC),]
c170_dc_top10_perc <- head(c170_dc_ordered, 17)

## Closeness centrality  
  
c170_cc <- subset(cluster170_cs, select = c("id", "CC"))
c170_cc_ordered <- c170_cc[order(-c170_cc$CC),]
c170_cc_top10_perc <- head(c170_cc_ordered, 17)

## Eigenvector centrality  
  
c170_ec <- subset(cluster170_cs, select = c("id", "EC"))
c170_ec_ordered <- c170_ec[order(-c170_ec$EC),]
c170_ec_top10_perc <- head(c170_ec_ordered, 17)

## merge all top10 centrality scores

library(reshape)
c170_list <- list(c170_dc_top10_perc, c170_cc_top10_perc, c170_ec_top10_perc)
c170_top10perc_data <- merge_recurse(c170_list)

## Remove the IDs that doesn't have all three centrality values

c170_top10perc_data_tofile <- na.omit(c170_top10perc_data)

write.table(c170_top10perc_data_tofile, file = "../../results/centrality_analysis_results/module8_p170/top10percent_genes_in_c170.txt", sep = "\t", row.names = FALSE, col.names = T, quote= FALSE)

####### To find central nodes in Module 9 (10% of 122 is 12)

cluster122_cs <- read.delim("../../results/centrality_analysis_results/module9_p122/centrality_scores.txt", header = T, sep = "\t")
names(cluster122_cs)[1] = "id"

## degree centrality

c122_dc <- subset(cluster122_cs, select = c("id", "DC"))
c122_dc_ordered <- c122_dc[order(-c122_dc$DC),]
c122_dc_top10_perc <- head(c122_dc_ordered, 12)

## Closeness centrality  
  
c122_cc <- subset(cluster122_cs, select = c("id", "CC"))
c122_cc_ordered <- c122_cc[order(-c122_cc$CC),]
c122_cc_top10_perc <- head(c122_cc_ordered, 12)

## Eigenvector centrality  
  
c122_ec <- subset(cluster122_cs, select = c("id", "EC"))
c122_ec_ordered <- c122_ec[order(-c122_ec$EC),]
c122_ec_top10_perc <- head(c122_ec_ordered, 12)

## merge all top10 centrality scores

library(reshape)
c122_list <- list(c122_dc_top10_perc, c122_cc_top10_perc, c122_ec_top10_perc)
c122_top10perc_data <- merge_recurse(c122_list)

## Remove the IDs that doesn't have all three centrality values

c122_top10perc_data_tofile <- na.omit(c122_top10perc_data)

write.table(c122_top10perc_data_tofile, file = "../../results/centrality_analysis_results/module9_p122/top10percent_genes_in_c122.txt", sep = "\t", row.names = FALSE, col.names = T, quote= FALSE)

####### To find central nodes in Module 10 (10% of 79 is 8)

cluster79_cs <- read.delim("../../results/centrality_analysis_results/module10_p79/centrality_scores.txt", header = T, sep = "\t")
names(cluster79_cs)[1] = "id"

## degree centrality

c79_dc <- subset(cluster79_cs, select = c("id", "DC"))
c79_dc_ordered <- c79_dc[order(-c79_dc$DC),]
c79_dc_top10_perc <- head(c79_dc_ordered, 8)

## Closeness centrality  
  
c79_cc <- subset(cluster79_cs, select = c("id", "CC"))
c79_cc_ordered <- c79_cc[order(-c79_cc$CC),]
c79_cc_top10_perc <- head(c79_cc_ordered, 8)

## Eigenvector centrality  
  
c79_ec <- subset(cluster79_cs, select = c("id", "EC"))
c79_ec_ordered <- c79_ec[order(-c79_ec$EC),]
c79_ec_top10_perc <- head(c79_ec_ordered, 8)

## merge all top10 centrality scores

library(reshape)
c79_list <- list(c79_dc_top10_perc, c79_cc_top10_perc, c79_ec_top10_perc)
c79_top10perc_data <- merge_recurse(c79_list)

## Remove the IDs that doesn't have all three centrality values

c79_top10perc_data_tofile <- na.omit(c79_top10perc_data)

write.table(c79_top10perc_data_tofile, file = "../../results/centrality_analysis_results/module10_p79/top10percent_genes_in_c79.txt", sep = "\t", row.names = FALSE, col.names = T, quote= FALSE)

####### To find central nodes in Module 11 (10% of 123 is 12)

cluster123_cs <- read.delim("../../results/centrality_analysis_results/module11_p123/centrality_scores.txt", header = T, sep = "\t")
names(cluster123_cs)[1] = "id"

## degree centrality

c123_dc <- subset(cluster123_cs, select = c("id", "DC"))
c123_dc_ordered <- c123_dc[order(-c123_dc$DC),]
c123_dc_top10_perc <- head(c123_dc_ordered, 12)

## Closeness centrality  
  
c123_cc <- subset(cluster123_cs, select = c("id", "CC"))
c123_cc_ordered <- c123_cc[order(-c123_cc$CC),]
c123_cc_top10_perc <- head(c123_cc_ordered, 12)

## Eigenvector centrality  
  
c123_ec <- subset(cluster123_cs, select = c("id", "EC"))
c123_ec_ordered <- c123_ec[order(-c123_ec$EC),]
c123_ec_top10_perc <- head(c123_ec_ordered, 12)

## merge all top10 centrality scores

library(reshape)
c123_list <- list(c123_dc_top10_perc, c123_cc_top10_perc, c123_ec_top10_perc)
c123_top10perc_data <- merge_recurse(c123_list)

## Remove the IDs that doesn't have all three centrality values

c123_top10perc_data_tofile <- na.omit(c123_top10perc_data)

write.table(c123_top10perc_data_tofile, file = "../../results/centrality_analysis_results/module11_p123/top10percent_genes_in_c123.txt", sep = "\t", row.names = FALSE, col.names = T, quote= FALSE)

####### To find central nodes in Module 12 (10% of 123 is 22)

cluster220_cs <- read.delim("../../results/centrality_analysis_results/module12_p220/centrality_scores.txt", header = T, sep = "\t")
names(cluster220_cs)[1] = "id"

## degree centrality

c220_dc <- subset(cluster220_cs, select = c("id", "DC"))
c220_dc_ordered <- c220_dc[order(-c220_dc$DC),]
c220_dc_top10_perc <- head(c220_dc_ordered, 22)

## Closeness centrality  
  
c220_cc <- subset(cluster220_cs, select = c("id", "CC"))
c220_cc_ordered <- c220_cc[order(-c220_cc$CC),]
c220_cc_top10_perc <- head(c220_cc_ordered, 22)

## Eigenvector centrality  
  
c220_ec <- subset(cluster220_cs, select = c("id", "EC"))
c220_ec_ordered <- c220_ec[order(-c220_ec$EC),]
c220_ec_top10_perc <- head(c220_ec_ordered, 22)

## merge all top10 centrality scores

library(reshape)
c220_list <- list(c220_dc_top10_perc, c220_cc_top10_perc, c220_ec_top10_perc)
c220_top10perc_data <- merge_recurse(c220_list)

## Remove the IDs that doesn't have all three centrality values

c220_top10perc_data_tofile <- na.omit(c220_top10perc_data)

write.table(c220_top10perc_data_tofile, file = "../../results/centrality_analysis_results/module12_p220/top10percent_genes_in_c220.txt", sep = "\t", row.names = FALSE, col.names = T, quote= FALSE)

####### To find central nodes in Module 13 (10% of 150 is 15)

cluster150_cs <- read.delim("../../results/centrality_analysis_results/module13_p150/centrality_scores.txt", header = T, sep = "\t")
names(cluster150_cs)[1] = "id"

## degree centrality

c150_dc <- subset(cluster150_cs, select = c("id", "DC"))
c150_dc_ordered <- c150_dc[order(-c150_dc$DC),]
c150_dc_top10_perc <- head(c150_dc_ordered, 15)

## Closeness centrality  
  
c150_cc <- subset(cluster150_cs, select = c("id", "CC"))
c150_cc_ordered <- c150_cc[order(-c150_cc$CC),]
c150_cc_top10_perc <- head(c150_cc_ordered, 15)

## Eigenvector centrality  
  
c150_ec <- subset(cluster150_cs, select = c("id", "EC"))
c150_ec_ordered <- c150_ec[order(-c150_ec$EC),]
c150_ec_top10_perc <- head(c150_ec_ordered, 15)

## merge all top10 centrality scores

library(reshape)
c150_list <- list(c150_dc_top10_perc, c150_cc_top10_perc, c150_ec_top10_perc)
c150_top10perc_data <- merge_recurse(c150_list)

## Remove the IDs that doesn't have all three centrality values

c150_top10perc_data_tofile <- na.omit(c150_top10perc_data)

write.table(c150_top10perc_data_tofile, file = "../../results/centrality_analysis_results/module13_p150/top10percent_genes_in_c150.txt", sep = "\t", row.names = FALSE, col.names = T, quote= FALSE)

####### To find central nodes in Module 14 (10% of 73 is 7)

cluster73_cs <- read.delim("../../results/centrality_analysis_results/module14_p73/centrality_scores.txt", header = T, sep = "\t")
names(cluster73_cs)[1] = "id"

## degree centrality

c73_dc <- subset(cluster73_cs, select = c("id", "DC"))
c73_dc_ordered <- c73_dc[order(-c73_dc$DC),]
c73_dc_top10_perc <- head(c73_dc_ordered, 7)

## Closeness centrality  
  
c73_cc <- subset(cluster73_cs, select = c("id", "CC"))
c73_cc_ordered <- c73_cc[order(-c73_cc$CC),]
c73_cc_top10_perc <- head(c73_cc_ordered, 7)

## Eigenvector centrality  
  
c73_ec <- subset(cluster73_cs, select = c("id", "EC"))
c73_ec_ordered <- c73_ec[order(-c73_ec$EC),]
c73_ec_top10_perc <- head(c73_ec_ordered, 7)

## merge all top10 centrality scores

library(reshape)
c73_list <- list(c73_dc_top10_perc, c73_cc_top10_perc, c73_ec_top10_perc)
c73_top10perc_data <- merge_recurse(c73_list)

## Remove the IDs that doesn't have all three centrality values

c73_top10perc_data_tofile <- na.omit(c73_top10perc_data)

write.table(c73_top10perc_data_tofile, file = "../../results/centrality_analysis_results/module14_p73/top10percent_genes_in_c73.txt", sep = "\t", row.names = FALSE, col.names = T, quote= FALSE)

```